apiVersion: v1
kind: Pod
metadata:
  name: devbox
spec:
  restartPolicy: Always
  containers:
    - name: devbox
      image: devbox:v1
      volumeMounts:
        - name: shared-volume
          mountPath: /var/shared
  volumes:
    - name: shared-volume
      hostPath:
        path: /Users/p2708440/src/docks/devbox/shared
