apiVersion: v1
kind: Pod
metadata:
  name: devbox
spec:
  containers:
    - name: devbox
      volumeMounts:
        - name: shared-volume
          mountPath: /var/shared
      image: devbox:v1
      command: 
        - sleep
        - infinity
  volumes:
    - name: shared-volume
      hostPath:
        path: /Users/p2708440/src/docks/devbox/shared
 
